version: '2.3'
services:
  q-server:
    build:
      context: ./build
    # image: tonlabs/q-server:latest
    container_name: q-server
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: '{{ VIRTUAL_HOST }}'
      VIRTUAL_PORT: '{{ VIRTUAL_PORT }}'
      Q_DATABASE_SERVER: '{{ Q_DATABASE_SERVER }}'
      Q_SLOW_DATABASE_SERVER: '{{ Q_SLOW_DATABASE_SERVER }}'
      Q_REQUESTS_MODE: '{{ Q_REQUESTS_MODE }}'
      Q_REQUESTS_SERVER: '{{ Q_REQUESTS_SERVER }}'
      Q_REQUESTS_TOPIC: '{{ Q_REQUESTS_TOPIC }}'
      Q_DATABASE_MAX_SOCKETS: '{{ Q_DATABASE_MAX_SOCKETS }}'
      Q_SLOW_DATABASE_MAX_SOCKETS: '{{ Q_SLOW_DATABASE_MAX_SOCKETS }}'
      Q_STATSD_SERVER: 'statsd:9125'
    networks:
      - proxy_nw
    expose:
      - "4000"
    mem_limit: 5G
    logging: 
      driver: gelf 
      options:
        gelf-address: "udp://localhost:12201"
        tag: "q-server"

networks:
  proxy_nw:
    external: true
