--
- name: proxy
  hosts: 
   - proxy
  remote_user: root
  roles:
    - pre-install
    - proxy

- name: web-root
  hosts: web-root
  remote_user: root
  roles:
    - pre-install
    - web-root

- name: arangodb
  hosts: arangodb
  remote_user: root
  roles:
    - pre-install
    - arangodb

- name: q-server
  hosts: q-server
  remote_user: root
  roles:
    - pre-install
    - q-server

- name: kafka
  hosts: kafka
  remote_user: root
  roles:
    - pre-install
    - kafka

- name: statsd
  hosts: statsd
  remote_user: root
  roles:
    - pre-install
    - statsd

- name: ton-node
  hosts: ton-node
  remote_user: root
  roles:
    - pre-install
    - ton-node

- name: ELK
  hosts: ELK
  remote_user: root
  roles:
    - pre-install
    - ELK

- name: monitoring-server
  hosts: monitoring-server
  remote_user: root
  roles:
    - pre-install
    - monitoring-server

- name: monitoring-node
  hosts: monitoring-node
  remote_user: root
  roles:
    - pre-install
    - monitoring-node
